### ISSUE TITLE
Dataset splitting strategy of the DailyAction-DVS

### ISSUE THREAD

**Issue by bochenxie** [qianhuiliu/SNN-action-recognition#2]
Hi, Qianhui. Thank you for sharing the DailyAction-DVS dataset.

Would you mind telling us the dataset splitting strategy (training and validation/testing) of DailyAction-DVS when you experiment? We hope you can also support an official dataset splitting strategy, since it can help other researchers compare with their methods on DailyAction-DVS using the same setup.

Again, thank you for your contribution very much. Hope to hear from you soon.

**Comment by booker-max** [comment]
hello, I also encountered this problem now, have you solved it?
